# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: RefMole

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
#    start_tag: '[%'
#    end_tag:   '%]'

sbcat_path: /home/dsheroh/src/sbcat/

sru:
  url: http://pub.lub.lu.se/sru?version=1.1&operation=searchRetrieve
  result_limit: 250

csl_engine:
  url: http://ubcsl.ub.uni-bielefeld.de/citenode.php
  format: html
  default_style: plos
  recs: 100
  type_map:
    article: article
    book chapter: chapter
    book editor: book
    book: book
    conference abstract: chapter
    conference paper: chapter
    conference publication: book
    encyclopedia article: article
    journal editor: article
    newspaper article: article
    patent: article
    preprint: preprint
    report: book
    review: article
    thesis: thesis
    working Paper: chapter
    Bi BachelorThesis: thesis
    Bi Dissertation: thesis
    Bi MasterThesis: thesis
    Bi PostdocThesis: thesis
