# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: RefMole

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# ****************************************************************************
# *** Note that local/non-CSL citation styles are processed using a        ***
# *** separate TT instance, defined in RefMole::CiteList::format_citations ***
# *** NOT the TT instance created by Dancer, so the following settings do  ***
# *** not apply to them                                                    ***
# ****************************************************************************
template: template_toolkit
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '<%'
    end_tag:   '%>'
    PLUGIN_BASE: RefMole::TT::Plugin

